"""
Report Templates — formatting helpers for research reports.
"""

from __future__ import annotations

from typing import Optional

from finra.agent.state import MarketData


def format_metrics_table(market: MarketData) -> str:
    """Format market metrics into a Markdown table."""
    rows = [
        ("Current Price", f"${market.current_price:.2f}", ""),
        ("Price Change", f"{market.price_change_pct:+.2f}%", ""),
        ("Market Cap", _format_large_number(market.market_cap), ""),
        ("", "", ""),
        ("P/E Ratio", f"{market.pe_ratio:.1f}", _rate_metric(market.pe_ratio, 15, 25)),
        ("P/S Ratio", f"{market.ps_ratio:.2f}", _rate_metric(market.ps_ratio, 3, 8)),
        ("P/B Ratio", f"{market.pb_ratio:.2f}", _rate_metric(market.pb_ratio, 1, 3)),
        ("Dividend Yield", f"{market.dividend_yield * 100:.2f}%" if market.dividend_yield else "N/A", ""),
        ("", "", ""),
        ("Revenue", _format_large_number(market.revenue), ""),
        ("Revenue Growth", f"{market.revenue_growth:+.1f}%", ""),
        ("Net Income", _format_large_number(market.net_income), ""),
        ("Free Cash Flow", _format_large_number(market.free_cash_flow), ""),
        ("", "", ""),
        ("Gross Margin", f"{market.gross_margin * 100:.1f}%" if market.gross_margin else "N/A", ""),
        ("Operating Margin", f"{market.operating_margin * 100:.1f}%" if market.operating_margin else "N/A", ""),
        ("Net Margin", f"{market.net_margin * 100:.1f}%" if market.net_margin else "N/A", ""),
        ("ROE", f"{market.roe * 100:.1f}%" if market.roe else "N/A", ""),
        ("Debt/Equity", f"{market.debt_to_equity:.1f}" if market.debt_to_equity else "N/A", ""),
    ]

    lines = ["| Metric | Value | |", "|--------|-------|-|"]
    for metric, value, rating in rows:
        if not metric and not value:
            lines.append("| | | |")
        else:
            lines.append(f"| {metric} | {value} | {rating} |")

    return "\n".join(lines)


REPORT_TEMPLATE = """# Investment Research Report: {ticker}

**Query:** {query}
**Date:** {date}
**Depth:** {depth}

---

## {verdict_emoji} Verdict: {verdict}
**Conviction: {conviction_score}/100**

---

## Executive Summary
{executive_summary}

## Conviction Breakdown
{conviction_breakdown}

## Key Metrics
{metrics_table}

## Technical Analysis
{technical_analysis}

## 🐂 Bull Case
{bull_points}

## 🐻 Bear Case
{bear_points}

## News & Sentiment
{news_sentiment}

## Sources
{sources}

---
*Generated by Financial Research Agent (FinRA) — Not financial advice.*
"""


def _format_large_number(value: float) -> str:
    """Format a number into human-readable large number notation."""
    if not value:
        return "N/A"
    abs_val = abs(value)
    sign = "-" if value < 0 else ""
    if abs_val >= 1e12:
        return f"{sign}${abs_val / 1e12:.2f}T"
    elif abs_val >= 1e9:
        return f"{sign}${abs_val / 1e9:.2f}B"
    elif abs_val >= 1e6:
        return f"{sign}${abs_val / 1e6:.2f}M"
    elif abs_val >= 1e3:
        return f"{sign}${abs_val / 1e3:.2f}K"
    else:
        return f"{sign}${abs_val:.2f}"


def _rate_metric(value: float, cheap: float, expensive: float) -> str:
    """Rate a valuation metric as Cheap/Fair/Expensive."""
    if not value:
        return ""
    if value <= cheap:
        return "🟢 Cheap"
    elif value <= expensive:
        return "🟡 Fair"
    else:
        return "🔴 Expensive"
